---
development:
  cloud_name: tomotod0747
  api_key: '296561478359114'
  api_secret: ev5Mt641ehH2E139GwZ7gi38gek
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: tomotod0747
  api_key: '296561478359114'
  api_secret: ev5Mt641ehH2E139GwZ7gi38gek
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: tomotod0747
  api_key: '296561478359114'
  api_secret: ev5Mt641ehH2E139GwZ7gi38gek
  enhance_image_tag: true
  static_image_support: false
